name = "SlowLife"
author = "Yeom03"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d0f542b6d5ca5f6ab8024dc0334c423fcbc18d9e76359144d229a95a788bf72"

[versions]
minecraft = "1.21.6"
neoforge = "21.6.20-beta"
