name = "SlowLife"
author = "Yeom03"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ECA260381FBE4D2BFCAD765A614D77A17EC0366A6984697EDA204AA26465F77"

[versions]
minecraft = "1.21.6"
neoforge = "21.6.20-beta"
