general = {disable_mod = false, hide_bossbar = true, shadow_text = true, auto_start = false, animationSpeed = 1.0, always_show_ping = false, hide_debug_crosshair = false, background_color = 1867534416, space_modules = true, always_show_profiler = false, animations = true, fontScale = 1.0, hide_sidebar = true, always_show_tps = false}
[[modules_right]]
	name = "system"
	name_color = 16755200
	value_color = 5636095
	lines = {opengl_version = false, allocation_rate = true, display = false, java_version = true, gpu_driver = false, memory_usage = true, allocated_memory = true, cpu = false, gpu_utilization = false, time = true, gpu = false}
	enabled = true
[[modules_right]]
	empty_lines = 1
	name = "empty"
	lines = {nothing = true}
	enabled = true
[[modules_right]]
	name = "target"
	name_color = 43775
	value_color = 16777045
	lines = {id_fluid = true, fluid_tags = true, block_states = true, targeted_block = true, block_tags = true, id_block = true, nothing = true, nothing2 = true, targeted_fluid = true, targeted_entity = true, fluid_states = true}
	enabled = true

[[modules_left]]
	name = "minecraft"
	name_color = 10506797
	value_color = 43520
	lines = {minecraft = true}
	enabled = true
[[modules_left]]
	color_high = 5635925
	color_med = 16777045
	name = "fps"
	lines = {fps = true}
	enabled = true
	color_low = 16733525
[[modules_left]]
	name = "graphics"
	name_color = 16755200
	value_color = 5636095
	lines = {shader = true, render_distance = true, graphics = true, clouds = true, biome_blend_radius = true}
	enabled = true
[[modules_left]]
	color_x = 16733525
	color_y = 5635925
	color_z = 5636095
	name = "coords"
	name_color = 16733525
	lines = {chunk_coords = true, player_coords = true, block_coords = true, absolute_velocity = false, velocity = true, chunk_relative_coords = true, horizontal_velocity = false}
	enabled = true
[[modules_left]]
	name = "location"
	name_color = 43520
	value_color = 5636095
	lines = {light = true, biome = true, rotation = true, facing = true, slime_chunk = true, local_difficulty = true, day_ticks = true, days_played = true, dimension = true, highest_block = true, highest_block_server = true, light_server = true}
	enabled = true
[[modules_left]]
	name = "entity"
	name_color = 16733525
	value_color = 16777045
	total_entities_color = 16755200
	lines = {entities = true, water_creature = true, underground_water_creature = true, ambient = true, particles = true, axolotls = true, creature = true, water_ambient = true, monster = true, misc = true}
	enabled = true
